config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
  resources :rooms
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, :capacity, presence: true
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @bookings = Booking.all
  end

  def show

  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html {redirect_to booking_url(@booking), notice: "Booking was successfully updated" }
      else
        format.html {render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html {redirect_to bookings_url, notice: "Booking was successfully deleted" }
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:room_id, :start, :end, :purpose, :user_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # before action sets room id in my params but only for the "show" and "edit" methods I've implemented below
  before_action :set_room, only: %i[show edit update destroy]
  def index
    @rooms = Room.all
  end

  def show
    
  end
  
  # action that shows page where I want to show form to create new room
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    # use "respond_to" to define different formats I want my app to respond to
    respond_to do |format|
       # if room is created
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was created successfully" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully deleted" }
    end
  end


  # private callback action to call at top of class so set current room value
  private
  def set_room
    @room = Room.find(params[:id])
  end

  private
  def room_params
    params.require(:room).permit(:name, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <div>
    <%= form.label :start, style: "display: block" %> 
    <%= form.datetime_field :start %> 
  </div>

  <div>
    <%= form.label :end, style: "display: block" %> 
    <%= form.datetime_field :end %> 
  </div>

  <div>
    <%= form.label :purpose, style: "display: block" %> 
    <%= form.text_field :purpose %> 
  </div>
  
  <div>
    <%= form.label :room, style: "display: block" %> 
    <%= form.collection_select :room_id, Room.all, :id, :name %> 
  </div>
  
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %> 
  </div>
  
  <div>
    <%= form.submit %> 
  </div>


<% end %>

app/views/bookings/edit.html.erb
<h2> Edit Booking </h2>

<%= render "form", booking: @booking %>

app/views/bookings/index.html.erb
<h2> List of Bookings </h2>

<% @bookings.each do |booking| %>
  <p>Start: <%= booking.start %></p>
  <p>End: <%= booking.end %></p>
  <p>Purpose: <%= booking.purpose %></p>
  <p>Room: 
    <%= link_to booking.room.name, booking.room %>
  </p>
<% end %>

<%= link_to "Create new booking", new_booking_path%>

app/views/bookings/new.html.erb
<h2> New Booking </h2>

<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<%= @booking.start %>
<%= @booking.end %>
<%= @booking.purpose %>
<%= @booking.room.name %>
<%= button_to "Delete this booking", @booking, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%# Adding simple css CDN for simple styling %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Adding error notices/notifications below  %>
    <p class="notice"><%= notice %> </p>
    <p class="alert"><%= alert %> </p>
    
    <%# Code below is responsible for rendering button options in the navbar %>
    <% if user_signed_in? %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
      <%= link_to "Bookings", bookings_path %>
      <%= link_to "Rooms", rooms_path %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
<% if room.errors.any? %>
  <div style="color: red" >
  <h2> <%= pluralize(room.errors.count, "errors") %> An error prohibited this room from saving </h2>
  <ul>
    <% room.errors.each do |error| %>
      <li> <%= error.full_message %> </li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :capacity, style: "display: block" %>
  <%= form.number_field :capacity %>
</div>

<div> 
  <%= form.submit %>
</div>

<% end %>

app/views/rooms/edit.html.erb
<h2> Edit Room </h2>

<%= render "form", room: @room%>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>

<p><%= link_to room.name, room %></p>

<p> Capacity 
  <%= room.capacity %>
</p>
<% end %>
<%= link_to "Create New Room", new_room_path %>

app/views/rooms/new.html.erb
<h1> New Room </h1>

<%= render "form", room: @room %>

app/views/rooms/show.html.erb
<%= @room.name %>
<%= @room.capacity %>
<%= button_to "Delete this room", @room, method: :delete %>

<% @room.bookings.each do |booking| %>
  <p>Start: <%= booking.start %></p>
  <p>End: <%= booking.end %></p>
  <p>Purpose: <%= booking.purpose %></p>
  <p><%= link_to "Bookings", booking %></p>
<% end %>